### ISSUE TITLE
123456

### ISSUE THREAD

**Issue by welder1976** [azerothcore/mod-bg-slaveryvalley#1]
http://www.modcraft.io/index.php?topic=10882.0

**Comment by FrancescoBorzi** [comment]
@welder1976 

![image](https://user-images.githubusercontent.com/75517/53950221-fe453d00-40cb-11e9-9057-02b00073adf1.png)


in https://github.com/azerothcore/mod-bg-slaveryvalley/blob/master/README.md

**Comment by Helias** [comment]
if you click on "Snoopzz" it redirects you in that post.

Anyway the code is not the same, the module is updated, with cleint-side patch and server-side code updated.
