### ISSUE TITLE
Failed to build on actual branch

### ISSUE THREAD

**Issue by Shadowveil-WotLK** [azerothcore/mod-bg-slaveryvalley#4]
The mod gave multiple errors on building the latest branch.
https://github.com/azerothcore/azerothcore-wotlk/commit/096b95a9bec94ded1aaae2c4094bcc9b996d23b4

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	605	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	573	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	513	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	313	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	294	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	287	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	278	
Error	C2039	'outErrorDb': is not a member of 'Log'	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp	269	
Error	C2678	binary '<<': no operator found which takes a left-hand operand of type 'WorldPacket' (or there is no acceptable conversion) (compiling source file A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp)	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.h	310	
Error	C2678	binary '<<': no operator found which takes a left-hand operand of type 'WorldPacket' (or there is no acceptable conversion) (compiling source file A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.cpp)	modules	A:\azerothcore-wotlk\modules\mod-bg-slaveryvalley\src\BattlegroundSV.h	309

**Comment by Shadowveil-WotLK** [comment]
@Helias could u give a look at this when u got some time? =)

thanks in advance! =D

**Comment by angrytoilet** [comment]
As of 3/5/2022 (24 days after initial issue report) the issue still persists.
The question is, are the ones you charge $150 for treated the same abandonware style?

**Comment by Helias** [comment]
mod-bg-slaveryvalley is totally open source I didn't charge anyone for this.

In past, it was open to AC rank contributor 3 and donator, but now it is totally open.

I am really sorry if I didn't update it, unfortunately I am in a busy period of my life.

**Comment by Helias** [comment]
Check now, @acidmanifesto fixed the build

**Comment by Shadowveil-WotLK** [comment]
kk will test and will let u know! =)
thanks for taking care about it tho! =D
rly appreciate that ^.^

**Comment by Shadowveil-WotLK** [comment]
Build succeeded now!
Thank you very much!!!! =D =D
I will close this issue now! =)
